[package]
name = "paper_search_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio_wasi = { version = "1.21", features = ["rt", "macros", "net", "time"]}
reqwest_wasi = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6.0"

